enum Types {
  SET_CURRENT_USER = 'commit/SET_CURRENT_USER',
  SET_CURRENT_REPO = 'commit/SET_CURRENT_REPO',

  GET_REPOS_REQUEST = 'commit/GET_REPOS_REQUEST',
  GET_REPOS_SUCCESS = 'commit/GET_REPOS_SUCCESS',
  GET_REPOS_ERROR = 'commit/GET_REPOS_ERROR',

  GET_COMMITS_REQUEST = 'commit/GET_COMMITS_REQUEST',
  GET_COMMITS_SUCCESS = 'commit/GET_COMMITS_SUCCESS',
  GET_COMMITS_ERROR = 'commit/GET_COMMITS_ERROR',
}

export default Types
