enum Types {
  SET_CURRENT_USER = 'issue/SET_CURRENT_USER',
  SET_CURRENT_REPO = 'issue/SET_CURRENT_REPO',

  GET_REPOS_REQUEST = 'issue/GET_REPOS_REQUEST',
  GET_REPOS_SUCCESS = 'issue/GET_REPOS_SUCCESS',
  GET_REPOS_ERROR = 'issue/GET_REPOS_ERROR',

  GET_ISSUES_REQUEST = 'issue/GET_ISSUES_REQUEST',
  GET_ISSUES_SUCCESS = 'issue/GET_ISSUES_SUCCESS',
  GET_ISSUES_ERROR = 'issue/GET_ISSUES_ERROR',

  GET_FILTERED_ISSUES_REQUEST = 'issue/GET_FILTERED_ISSUES_REQUEST',
}

export default Types
